package com.github.wenweihu86.raft.util;

public enum EVENT {
	CONVERT_STATUS,
	BECOME_LEADER,
	APPEND_DATA,
	APPEND_NODE,
	REMOVE_NODE,
	START_PRE_VOTE,
	FINISH_PRE_VOTE,
	START_FORMAL_VOTE,
	FINISH_FORMAL_VOTE
}
